apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profile | default "prod" | quote }}
  SERVER_PORT: "8080"

  # Database non-secret configs
  DB_HOST: {{ .Values.db.host | quote }}
  DB_NAME: {{ .Values.db.name | quote }}

  # JVM tuning (prod safe defaults)
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
