apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.db.user | b64enc | quote }}
  password: {{ .Values.db.password | default "change-me" | b64enc | quote }}
