apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<your-org>/petclinic-gitops.git
    targetRevision: main
    path: charts/petclinic
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod

  syncPolicy:
    automated:
      prune: false     # prod safety
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
